<a href="https://colab.research.google.com/github/Rushikesh419/NLP/blob/main/extractin_feature_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text=['This is a line',
      'This is another line',
      'Completly different line']

In [14]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [4]:
# help(CountVectorizer)

In [17]:
cv=CountVectorizer()

In [18]:
sparce_metrix=cv.fit_transform(text)

In [19]:
sparce_metrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [20]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completly': 1, 'different': 2}

In [15]:
tfidf=TfidfTransformer()

In [21]:
sparce_metrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [23]:
results=tfidf.fit_transform(sparce_metrix)

In [25]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [26]:
# all of above in one step
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tv=TfidfVectorizer()

In [29]:
tv_results=tv.fit_transform(text)

In [31]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])